answer:
  swagger-open: true #是否开启swagger (true/false)


rest:
  auth-open: true
  sign-open: true

jwt:
  header: Authorization
  secret: mySecret
  expiration: 7200      #1天 单位:秒 86400
  auth-path: auth
  md5-key: randomKey

swagger:
  enable: true # 是否开启 swagger 调试  true 开启，false 关闭

#####################################################################
########################  特殊校验开启开关  ##########################
#####################################################################
specialValidator:
  enable: true # 是否开启 特殊校验 调试  true 开启，false 关闭


###################  项目启动端口  ###################
server:
  port: 6080




###################  spring配置  ###################
spring:
  redis:
    host: localhost
    port: 6379
    password: pwd666
  profiles:
    active: dev



###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:com/etycx/answer/rest/**/mapping/*.xml
  typeAliasesPackage: com.etycx.answer.rest.remote.entity
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用

---

##########################################################
###################  开发环境的profile  ###################
##########################################################
spring:
  profiles: dev
  datasource:
      url: jdbc:mysql://localhost:3306/answer?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: pwd666
      filters: log4j,wall,mergeStat

logging:
  level.root: info
  level.com.etycx: debug

---



